### ISSUE TITLE
Disk cache problem

### ISSUE THREAD

**Issue by onuryurtturk** [nostra13/Android-Universal-Image-Loader#1039]
Im using uil in different activities to cache many images. Everything is okay if I cache to disk only in Main Activity but if I cache in Main Activity and some other activities, some cached images not showing in Main activity and giving "cannot resolve host error" in offline mode (without internet). I guess, caching in other activities prevents some image cache in Main activity because uil doesnt find disk cache and trying to get image from the internet so i getting host error. How can i handle this? Also i cant cache all images in Main activity. Same issue is existing in that case.

Im using this with async task;
Sorry for my english, thanks...

        @Override
        protected JSONArray doInBackground(String... params) {

          //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            for (int i= 0; i < allChannel.size(); i++) {
                   ImageLoader.getInstance().loadImage((allChannel.get(i)).getImage_url(),new SimpleImageLoadingListener());             

                }
          //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

            }

and DisplayOptions like this;

  options = new DisplayImageOptions.Builder()
                .showImageOnFail(R.drawable.ic_error)
                .cacheInMemory(true)
                .cacheOnDisk(true)
                .considerExifParams(true)
                .bitmapConfig(Bitmap.Config.RGB_565)
                .imageScaleType(ImageScaleType.EXACTLY)
                .build();

        ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(context)
                .defaultDisplayImageOptions(options)
                .memoryCacheSize(50 * 1024 * 1024)
                .diskCacheSize(50 * 1024 * 1024)
                .threadPoolSize(5)
                .writeDebugLogs()
                .build();

**Comment by nostra13** [comment]
stacktrace?

**Comment by onuryurtturk** [comment]
This time I got timedout error...

```xml
07-12 14:58:08.734  20791-21480/com.batunet.projectb E/ImageLoader﹕ recvfrom failed: ETIMEDOUT (Connection timed out)
    java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
            at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:552)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:516)
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
            at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
            at java.io.BufferedInputStream.read(BufferedInputStream.java:304)
            at libcore.net.http.FixedLengthInputStream.read(FixedLengthInputStream.java:45)
            at java.io.BufferedInputStream.read(BufferedInputStream.java:304)
            at com.nostra13.universalimageloader.core.assist.ContentLengthInputStream.read(ContentLengthInputStream.java:65)
            at com.nostra13.universalimageloader.utils.IoUtils.copyStream(IoUtils.java:77)
            at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiscCache.save(LruDiscCache.java:155)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:273)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:229)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
            at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:267)
            at com.nostra13.universalimageloader.core.ImageLoader.loadImage(ImageLoader.java:483)
            at com.nostra13.universalimageloader.core.ImageLoader.loadImage(ImageLoader.java:444)
            at com.nostra13.universalimageloader.core.ImageLoader.loadImageSync(ImageLoader.java:557)
            at com.nostra13.universalimageloader.core.ImageLoader.loadImageSync(ImageLoader.java:498)
            at com.batunet.projectb.SettingsActivity$cacheMedia.doInBackground(SettingsActivity.java:184)
            at com.batunet.projectb.SettingsActivity$cacheMedia.doInBackground(SettingsActivity.java:173)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: libcore.io.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
            at libcore.io.Posix.recvfromBytes(Native Method)
            at libcore.io.Posix.recvfrom(Posix.java:136)
            at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:513)
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
            at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
            at java.io.BufferedInputStream.read(BufferedInputStream.java:304)
            at libcore.net.http.FixedLengthInputStream.read(FixedLengthInputStream.java:45)
            at java.io.BufferedInputStream.read(BufferedInputStream.java:304)
            at com.nostra13.universalimageloader.core.assist.ContentLengthInputStream.read(ContentLengthInputStream.java:65)
            at com.nostra13.universalimageloader.utils.IoUtils.copyStream(IoUtils.java:77)
            at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiscCache.save(LruDiscCache.java:155)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:273)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:229)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
            at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:267)
            at com.nostra13.universalimageloader.core.ImageLoader.loadImage(ImageLoader.java:483)
            at com.nostra13.universalimageloader.core.ImageLoader.loadImage(ImageLoader.java:444)
            at com.nostra13.universalimageloader.core.ImageLoader.loadImageSync(ImageLoader.java:557)
            at com.nostra13.universalimageloader.core.ImageLoader.loadImageSync(ImageLoader.java:498)
            at com.batunet.projectb.SettingsActivity$cacheMedia.doInBackground(SettingsActivity.java:184)
            at com.batunet.projectb.SettingsActivity$cacheMedia.doInBackground(SettingsActivity.java:173)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
07-12 14:58:08.742  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.742  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/559f7ab11511c.jpg_600x1024]
07-12 14:58:08.750  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/559f7ab11511c.jpg_600x1024]
07-12 14:58:08.750  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/559f7ab11511c.jpg_600x1024]
07-12 14:58:08.750  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.765  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.765  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/559f7c4ce6e14.jpg_600x1024]
07-12 14:58:08.765  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/559f7c4ce6e14.jpg_600x1024]
07-12 14:58:08.765  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/559f7c4ce6e14.jpg_600x1024]
07-12 14:58:08.773  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.773  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.781  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/559f7cae79c06.jpg_600x1024]
07-12 14:58:08.781  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/559f7cae79c06.jpg_600x1024]
07-12 14:58:08.781  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/559f7cae79c06.jpg_600x1024]
07-12 14:58:08.789  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.796  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.796  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/556fdc15aaad9.png_600x1024]
07-12 14:58:08.796  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/556fdc15aaad9.png_600x1024]
07-12 14:58:08.796  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/556fdc15aaad9.png_600x1024]
07-12 14:58:08.804  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.804  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.812  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/559f76ad6f32d.jpg_600x1024]
07-12 14:58:08.812  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/559f76ad6f32d.jpg_600x1024]
07-12 14:58:08.812  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/559f76ad6f32d.jpg_600x1024]
07-12 14:58:08.835  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.859  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.859  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/559f7800be441.jpg_600x1024]
07-12 14:58:08.859  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/559f7800be441.jpg_600x1024]
07-12 14:58:08.859  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/559f7800be441.jpg_600x1024]
07-12 14:58:08.875  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.882  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.890  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/556fdc1492781.png_600x1024]
07-12 14:58:08.890  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/556fdc1492781.png_600x1024]
07-12 14:58:08.890  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/556fdc1492781.png_600x1024]
07-12 14:58:08.890  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.898  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.898  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/559e7ed4dee90.jpg_600x1024]
07-12 14:58:08.898  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/559e7ed4dee90.jpg_600x1024]
07-12 14:58:08.898  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/559e7ed4dee90.jpg_600x1024]
07-12 14:58:08.898  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.898  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.898  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/559f78e764b1b.jpg_600x1024]
07-12 14:58:08.898  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/559f78e764b1b.jpg_600x1024]
07-12 14:58:08.898  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/559f78e764b1b.jpg_600x1024]
07-12 14:58:08.906  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.906  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.906  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/558122c866b1d.png_600x1024]
07-12 14:58:08.906  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/558122c866b1d.png_600x1024]
07-12 14:58:08.906  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/558122c866b1d.png_600x1024]
07-12 14:58:08.906  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.906  20791-20791/com.batunet.projectb D/ProgressBar﹕ setProgress = 0
07-12 14:58:08.914  20791-20791/com.batunet.projectb D/ProgressBar﹕ setProgress = 0, fromUser = false
07-12 14:58:08.914  20791-20791/com.batunet.projectb D/ProgressBar﹕ mProgress = 0mIndeterminate = false, mMin = 0, mMax = 100
07-12 14:58:08.914  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.914  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/559f79570ccf0.jpg_600x1024]
07-12 14:58:08.914  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/559f79570ccf0.jpg_600x1024]
07-12 14:58:08.914  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/559f79570ccf0.jpg_600x1024]
07-12 14:58:08.921  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.921  20791-20791/com.batunet.projectb D/ImageLoader﹕ Load image from memory cache [http://url/uploads/558143e25e8c7.jpg_600x1024]
07-12 14:58:08.929  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.929  20791-21480/com.batunet.projectb D/ImageLoader﹕ Start display image task [http://url/uploads/559f79e8363c2.jpg_600x1024]
07-12 14:58:08.929  20791-21480/com.batunet.projectb D/ImageLoader﹕ Load image from network [http://url/uploads/559f79e8363c2.jpg_600x1024]
07-12 14:58:08.929  20791-21480/com.batunet.projectb D/ImageLoader﹕ Cache image on disk [http://url/uploads/559f79e8363c2.jpg_600x1024]
07-12 14:58:08.937  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
07-12 14:58:08.937  20791-20791/com.batunet.projectb I/System.out﹕ 0URL1
07-12 14:58:08.937  20791-21480/com.batunet.projectb E/ImageLoader﹕ Unable to resolve host "url": No address associated with hostname
```

**Comment by onuryurtturk** [comment]
any examples for multiple activities and async tasks with uil?

**Comment by nostra13** [comment]
Multiple activities without async tasks - in sample app (https://github.com/nostra13/Android-Universal-Image-Loader/tree/master/sample)

**Comment by onuryurtturk** [comment]
Thanks i already took a look to them...Im trying to achieve that; In a splash screen im getting some json datas and cache some images to disk. In logs it seems everything is okay when internet is not connected. But if i try to access and use it in adapter it seems onloadingfailed method is calling. Any idea ? about async tasks

**Comment by burakkilic** [comment]
+1
