### ISSUE TITLE
On API <17 getting a FrameLayout params exception cast

### ISSUE THREAD

**Issue by AnthonyUccello** [nostra13/Android-Universal-Image-Loader#1050]
When I try to open my library on devices using API's less than 17 I get a crash. 

But above that it works fine. Is there a support library we need to use when casting from one to the other if the API is under 17?

None of my code is called in the stack trace.

My code:

```java

//I do NOT call this directly, the listview decides when re use a convert view and passes it accordingly
        @Override
        public View getView(int position, View convertView, ViewGroup parent)
        {
            final ViewHolder holder;
            View view = convertView;
            if (view == null)
            {
                view = new ReusableGridViewView(parent.getContext());

                holder = new ViewHolder();
                assert view != null;
                holder.imageView = ((ReusableGridViewView)view).imageView;
                holder.progressBar = ((ReusableGridViewView)view).progressBar;
                holder.imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
                view.setTag(holder);
            } else {
                holder = (ViewHolder) view.getTag();
            }

            //System.out.println(" " + holder + " ||| " + holder.imageView);
            ImageLoader.getInstance()
                    .displayImage(IMAGE_URLS[position], holder.imageView, options, new SimpleImageLoadingListener()
                    {
                        @Override
                        public void onLoadingStarted(String imageUri, View view)
                        {
                            holder.progressBar.setProgress(0);
                            holder.progressBar.setVisibility(View.VISIBLE);
                        }

                        @Override
                        public void onLoadingFailed(String imageUri, View view, FailReason failReason)
                        {
                            holder.progressBar.setVisibility(View.GONE);
                        }

                        @Override
                        public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage)
                        {
                            holder.progressBar.setVisibility(View.GONE);
                        }

                    }, new ImageLoadingProgressListener()
                    {
                        @Override
                        public void onProgressUpdate(String imageUri, View view, int current, int total)
                        {
                            holder.progressBar.setProgress(Math.round(100.0f * current / total));
                        }
                    });

            //set all as unselected
            ((ReusableGridViewView) view).removeSelectionBorder();
            for(int i = 0; i < SELECTED_IMAGES.length; i++)
            {
                if(SELECTED_IMAGES[i] == position)
                {
                    //set cell to selected
                    ((ReusableGridViewView) view).addSelectionBorder();
                }
            }
            return view;
        }
```

Here is my reusable view.
```java
//Special class that works with the UIL
    //The holder gets re-used and gets the new properties from this
    static class ReusableGridViewView extends FrameLayout
    {
        public ImageView imageView;
        public ProgressBar progressBar;

        public ReusableGridViewView(Context context)
        {
            super(context);

            setLayoutParams(new LayoutParams((int)(0.325* ViewHelper.screenWidthPX(context)),(int)(0.325* ViewHelper.screenWidthPX(context))));

            imageView = new ImageView(context);
            //Making changes to imageView doesn't work here, need to put changes in the HOLDER (not sure why)
            progressBar = new ProgressBar(context);

            addView(imageView);
            addView(progressBar);
        }

        public void addSelectionBorder()
        {
            int border = 8;
            setPadding(border,border,border,border);
            setBackgroundColor(Colors.BLUE);
        }

        public void removeSelectionBorder()
        {
            int border = 0;
            setPadding(border,border,border,border);
            setBackgroundColor(Colors.LIGHT_BLACK);
        }
    }
```

Here is the stack trace

```java
FATAL EXCEPTION: main
    java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
            at android.widget.GridView.onMeasure(GridView.java:1032)
            at android.view.View.measure(View.java:15286)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:617)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:399)
            at android.view.View.measure(View.java:15286)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:617)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:399)
            at android.view.View.measure(View.java:15286)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4832)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:15286)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4832)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
            at android.view.View.measure(View.java:15286)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4832)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2269)
            at android.view.View.measure(View.java:15286)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2094)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1256)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1486)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1154)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4667)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:734)
            at android.view.Choreographer.doCallbacks(Choreographer.java:560)
            at android.view.Choreographer.doFrame(Choreographer.java:529)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:719)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5454)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by AnthonyUccello** [comment]
Its the ` static class ReusableGridViewView extends FrameLayout` that is getting cast and failing. If I change this class to a LinearLayout it also crashes but the message exception changes to saying  
`android.widget.LinearLayout$LayoutParams` etc.

**Comment by AnthonyUccello** [comment]
Solution:

So it turns out that on API < 17 FrameLayout can't be cast correctly to AbsListView params.

What I did was set AbsListView LayoutParams instead of FrameLayout params:
```
    setLayoutParams(new AbsListView.LayoutParams(100,100);
````
