### ISSUE TITLE
Errors loading images from dropbox

### ISSUE THREAD

**Issue by alexblack** [nostra13/Android-Universal-Image-Loader#1059]
A small # of my users are unable to load images from dropbox, I get emails from them about it and stack traces like this:

http://crashes.to/s/7d346b4052e

java.lang.Exception: Failed to copy logo from file:///storage/emulated/0/Android/data/com.dropbox.android/files/scratch/business/Logos%20%26%20Tags/GEMMCRAFTlite.png, failType: IO_ERROR, mimeType: null
       at com.aadhk.woinvoice.util.LogoUtils$1.onLoadingFailed(ProGuard:137)
       at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask$2.run(ProGuard:350)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5506)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.dropbox.android/files/scratch/business/Logos%20%26%20Tags/GEMMCRAFTlite.png: open failed: ENOENT (No such file or directory)
       at libcore.io.IoBridge.open(IoBridge.java:409)
       at java.io.FileInputStream.(FileInputStream.java:78)
       at java.io.FileInputStream.(FileInputStream.java:105)
       at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromFile(ProGuard:160)
       at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(ProGuard:88)
       at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.getImageStream(ProGuard:93)
       at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(ProGuard:73)
       at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(ProGuard:264)
       at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(ProGuard:237)
       at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(ProGuard:135)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
       at libcore.io.Posix.open(Posix.java)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
       at libcore.io.IoBridge.open(IoBridge.java:393)
       at java.io.FileInputStream.(FileInputStream.java:78)
       at java.io.FileInputStream.(FileInputStream.java:105)
       at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromFile(ProGuard:160)
       at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(ProGuard:88)
       at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.getImageStream(ProGuard:93)
       at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(ProGuard:73)
       at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(ProGuard:264)
       at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(ProGuard:237)
       at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(ProGuard:135)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by alexblack** [comment]
Any thoughts on this? I'd love to be able to load images from dropbox for my users.
