### ISSUE TITLE
what happen if one imageloader called many times?

### ISSUE THREAD

**Issue by d7coders** [nostra13/Android-Universal-Image-Loader#1085]
what happen if one imageloader with same parameters called many times?
for example what happen if this run

for(int i=0 ; i<10 ; i++)
    imageLoader.displayImage(url, iv_cover, Global.options);

**Comment by nostra13** [comment]
9 first task will be cancelled, last one will display image.

**Comment by d7coders** [comment]
I have GridView and inside it I have image loader  , but getview(); calls many times so that why I asked the question , but I have this error in catlogs



ImageLoader﹕ Too many redirects
    java.net.ProtocolException: Too many redirects
            at libcore.net.http.HttpURLConnectionImpl.processResponseHeaders(HttpURLConnectionImpl.java:377)
            at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:301)
            at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:495)
            at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromNetwork(BaseImageDownloader.java:117)
            at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:88)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:274)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:230)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)

**Comment by d7coders** [comment]
too many of this , too manyyyyyyyyyyy

**Comment by nostra13** [comment]
Maybe something wrong with your URLs.
