### ISSUE TITLE
java.lang.Error in LoadAndDisplayImageTask$TaskCancelledException 

### ISSUE THREAD

**Issue by nightbear1009** [nostra13/Android-Universal-Image-Loader#1096]
hi, 
I find a crash in my app as below, it seems wired. There is a try-catch in LoadAndDisplayImageTask.java but my app still crash, do you have any idea about this issue?

__crash device is__ 
XIAOMI - HM NOTE 1W
MEITU - MEITU2
FOXCONN - INFOCUS M320

__crash os version__
Android 4.2.2

__use imageloader version__
1.9.4

java.lang.Error: com.nostra13.universalimageloader.core.LoadAndDisplayImageTask$TaskCancelledException 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1086) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
      at java.lang.Thread.run(Thread.java:838) 
Caused by: com.nostra13.universalimageloader.core.LoadAndDisplayImageTask$TaskCancelledException 
      at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.checkViewCollected(SourceFile:410) 
      at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.checkTaskNotActual(SourceFile:395) 
      at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(SourceFile:139) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
      at java.lang.Thread.run(Thread.java:838)

**Comment by beena-patel** [comment]
Hi...
Find the same crash issue in my app.
Android version : 5.0.2
use imageloader version :1.9.3

 com.nostra13.universalimageloader.core.LoadAndDisplayImageTask$TaskCancelledException
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.checkViewReused(LoadAndDisplayImageTask.java:416)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.checkTaskNotActual(LoadAndDisplayImageTask.java:386)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:236)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:820)

**Comment by pmkhue** [comment]
Hi 
I has crashed too. That fixed in build 1.9.5 ?
