### ISSUE TITLE
NullPointerException in LruDiscCache

### ISSUE THREAD

**Issue by Vaxx88** [nostra13/Android-Universal-Image-Loader#1112]
Hi today I noticed strange crash in android developer console
java.lang.NullPointerException
	at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiscCache.get(SourceFile:124)
	at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(SourceFile:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:864)

Device: HTC Desire 820 (htc_a51ul)
Library Version: 1.9.2
Android Version: Android 4.4

it seems that cache reference was null. I do not call clear() or close() manually. Probably initCache() left cache reference null.

**Comment by jakubzieba** [comment]
I have new issue
ava.lang.NullPointerException: Attempt to invoke virtual method 'com.c.a.a.a.a.a.g com.c.a.a.a.a.a.a.a(java.lang.String)' on a null object reference
	at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiscCache.get(SourceFile:124)
	at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(SourceFile:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

Device: HTC One (m7)
Library Version: 1.9.2
Android Version: Android 5.0
