### ISSUE TITLE
一个url引发的问题

### ISSUE THREAD

**Issue by lyf571321556** [nostra13/Android-Universal-Image-Loader#1130]
http://miniwing.com/UserCentralSystemApi/api/user/avatar/download/7bc1dd305a6b4defb4a14a07d7b8af46/8ac63c9d2404fae0ba52e96da2cd0220  这个url 可以再浏览器打开，自己写的下载程序也能正常下载到图片文件 但是在使用框架的时候始终无法正常显示 跟踪源码发现打开这个链接的时候读取不到流

**Comment by lyf571321556** [comment]
8798-24497/com.nostra13.universalimageloader E/ImageLoader﹕ failed to connect to lh6.googleusercontent.com/216.58.197.97 (port 443) after 5000ms
    java.net.SocketTimeoutException: failed to connect to lh6.googleusercontent.com/216.58.197.97 (port 443) after 5000ms
            at libcore.io.IoBridge.connectErrno(IoBridge.java:159)
            at libcore.io.IoBridge.connect(IoBridge.java:112)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
            at java.net.Socket.connect(Socket.java:842)
            at libcore.net.http.HttpConnection.<init>(HttpConnection.java:76)
            at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
            at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
            at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
            at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
            at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:315)
            at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:461)
            at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:442)
            at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
            at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
            at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
            at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:486)
            at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
            at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromNetwork(BaseImageDownloader.java:117)
            at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:88)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:274)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:230)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)

官方demo 也会超时

**Comment by TIanmu** [comment]
访问超时了，这是网页那头的错误，你可以考虑设置一下超时时间。
ImageLoaderConfiguration的imageDownloader

**Comment by VernonLee** [comment]
我也遇到这个问题，设置超时时间也没有用

**Comment by AndiosDev2013** [comment]
@channel

Anybody found solution now for above issue?
I faced same issue on following URL.

https://i1.sndcdn.com/avatars-000118160419-u2ii1a-large.jpg
https://i1.sndcdn.com/artworks-000096618343-fgxk04-large.jpg 

Specially, this issue was occurred on Android 5.0+, I think there is some issue on HTTPS images.
