### ISSUE TITLE
Not expected Out of Memory

### ISSUE THREAD

**Issue by mr-procrastinator** [nostra13/Android-Universal-Image-Loader#1141]
I've faced with really strange issue during image loading. I see several crash log when application could not allocate ~ 1Mb for image, whereas it have about 16MB of free Memory and 468MB free not allocated.

```java.lang.OutOfMemoryError: Failed to allocate a 1166412 byte allocation with 16777120 free bytes and 468MB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:745)
    at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:566)
    at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1014)
    at android.content.res.Resources.loadDrawableForCookie(Resources.java:3730)
    at android.content.res.Resources.loadDrawable(Resources.java:3603)
    at android.content.res.Resources.getDrawable(Resources.java:1852)
    at android.content.res.Resources.getDrawable(Resources.java:1818)
    at com.nostra13.universalimageloader.core.DisplayImageOptions.getImageOnLoading(DisplayImageOptions.java:134)
    at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:257)
    at com.nostra13.universalimageloader.core.ImageLoader.loadImage(ImageLoader.java:483)
    at com.nostra13.universalimageloader.core.ImageLoader.loadImage(ImageLoader.java:419)```

Could someone explain me why such issue could occur?

**Comment by hufozhu** [comment]
I face this error after I upgrade to 1.9.4

**Comment by varunrramani** [comment]
We also have the same issue.

![2016-09-09](https://cloud.githubusercontent.com/assets/12987631/18384252/304673ce-76a7-11e6-97a7-833292086a79.png)

Size of the Array highlighted increases every time the app is opened, which increases the Heap memory. The Array highlighted is the Bitmap array where the images are stored by UIL.
