### ISSUE TITLE
java.lang.IllegalStateException: cache is closed

### ISSUE THREAD

**Issue by lee0921** [nostra13/Android-Universal-Image-Loader#1147]
Caused by: java.lang.IllegalStateException: cache is closed
    at com.cubic.autohome.common.view.image.cache.disc.impl.ext.DiskLruCache.checkNotClosed(DiskLruCache.java:648)
    at com.cubic.autohome.common.view.image.cache.disc.impl.ext.DiskLruCache.get(DiskLruCache.java:419)
    at com.cubic.autohome.common.view.image.cache.disc.impl.ext.LruDiskCache.get(LruDiskCache.java:134)
    at com.cubic.autohome.common.view.image.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:73)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)

**Comment by coding0man** [comment]
java.lang.IllegalStateException: cache is closed
	com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache.checkNotClosed(DiskLruCache.java:642)
	com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache.get(DiskLruCache.java:413)
	com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiskCache.get(LruDiskCache.java:133)
	com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:72)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	java.lang.Thread.run(Thread.java:833)
