### ISSUE TITLE
E/ImageLoader: UIL doesn't support scheme(protocol) by default

### ISSUE THREAD

**Issue by Elbakkali** [nostra13/Android-Universal-Image-Loader#1150]
Can't display image from url, can you please help me figure out what i'm doing wrong ? thank you in advance.

========================================================================

12-27 14:03:11.323 26309-26347/com.makemyandroidapp.example.stacksites E/ImageLoader: UIL doesn't support scheme(protocol) by default [
                                                                                              http://parlonsgeek.com/Flags/United-States.png
                                                                                            ]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
                                                                                      java.lang.UnsupportedOperationException: UIL doesn't support scheme(protocol) by default [
                                                                                              http://parlonsgeek.com/Flags/United-States.png
                                                                                            ]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
                                                                                          at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromOtherSource(BaseImageDownloader.java:206)
                                                                                          at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:95)
                                                                                          at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.saveImageOnDisc(LoadAndDisplayImageTask.java:299)
                                                                                          at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:237)
                                                                                          at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:149)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:841)
12-27 14:03:11.323 26309-26309/com.makemyandroidapp.example.stacksites I/StackSites: getView pos = 4
12-27 14:03:11.323 26309-26309/com.makemyandroidapp.example.stacksites I/StackSites: getView pos = 5

**Comment by weblu2000** [comment]
have you found the error?

**Comment by Elbakkali** [comment]
No, unfortunately i haven't.
