### ISSUE TITLE
anr when I directly load image by method  "loadImageSync" 

### ISSUE THREAD

**Issue by mejonzhan** [nostra13/Android-Universal-Image-Loader#1158]
at java.lang.Object.wait(Object.java:364)
  at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.waitIfPaused(LoadAndDisplayImageTask.java:188)
  at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:121)
  at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:268)
  at com.nostra13.universalimageloader.core.ImageLoader.loadImage(ImageLoader.java:484)
  at com.nostra13.universalimageloader.core.ImageLoader.loadImage(ImageLoader.java:445)
  at com.nostra13.universalimageloader.core.ImageLoader.loadImageSync(ImageLoader.java:558)
  at com.nostra13.universalimageloader.core.ImageLoader.loadImageSync(ImageLoader.java:499)
  at com.be.fly.ui.LogoActivity.onCreate(LogoActivity.java:104)

I think when I use loadImageSync that it directly load image from disk or cache, don't need to waitIfPaused

**Comment by maheshamle** [comment]
Hey, have you found out the solution on that?
