### ISSUE TITLE
unexpected end of stream

### ISSUE THREAD

**Issue by mejonzhan** [nostra13/Android-Universal-Image-Loader#1161]
java.net.ProtocolException: unexpected end of stream
W/System.err(10397):    at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.defineImageSizeAndRotation(BaseImageDecoder.java:106)
W/System.err(10397):    at java.io.BufferedInputStream.read(BufferedInputStream.java:288)
W/System.err(10397):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(10397):    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err(10397):    at java.io.InputStream.read(InputStream.java:162)
W/System.err(10397):    at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:613)
W/System.err(10397):    at java.io.InputStream.read(InputStream.java:162)
W/System.err(10397):    at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:81)
W/System.err(10397):    at java.io.BufferedInputStream.read(BufferedInputStream.java:288)
W/System.err(10397):    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:137)
W/System.err(10397):    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err(10397):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(10397):    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err(10397):    at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:389)
W/System.err(10397):    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:137)
W/System.err(10397):    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err(10397):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(10397):    at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:613)
W/System.err(10397):    at java.io.InputStream.read(InputStream.java:162)
W/System.err(10397):    at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:81)
W/System.err(10397):    at java.io.BufferedInputStream.read(BufferedInputStream.java:288)
W/System.err(10397):    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:137)
W/System.err(10397):    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err(10397):    at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:389)
W/System.err(10397):    at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.defineImageSizeAndRotation(BaseImageDecoder.java:106)
W/System.err(10397):    at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
W/System.err(10397):    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:137)
W/System.err(10397):    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err(10397):    at java.io.InputStream.read(InputStream.java:162)
W/System.err(10397):    at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:81)

**Comment by mejonzhan** [comment]
loop print this error  in a thread when I load a jpg file, but the real file is gif format.
