### ISSUE TITLE
ImageLoader: Unable to resolve host "xxxx.com": No address associated with hostname

### ISSUE THREAD

**Issue by leveychen** [nostra13/Android-Universal-Image-Loader#1170]
ImageLoader: Unable to resolve host "xxxx.com": No address associated with hostname
 and

````java
ImageLoader: null
                                                           java.io.EOFException
                                                               at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
                                                               at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
                                                               at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
                                                               at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:636)
                                                               at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:397)
                                                               at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:341)
                                                               at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:509)
                                                               at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromNetwork(BaseImageDownloader.java:117)
                                                               at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:88)
                                                               at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.getImageStream(BaseImageDecoder.java:98)
                                                               at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:74)
                                                               at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:265)
                                                               at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:238)
                                                               at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)
````

**Comment by euri16** [comment]
I'm experiencing just the same behaviour.

**Comment by niceteg** [comment]
Hi,

I have recently tried this stuff and it helped me, that's no joke! Read more here <http://advance.levenstudio.com/lnagstmt>

Sincerely yours, teg@ukr.net

**Comment by niceteg** [comment]
Hello, 

I've read a nice and informative  article about some stuff you may really like, you can  find more  info here <http://guide.ficibakim.com/lnlkizkc>

Yours, teg

**Comment by niceteg** [comment]
Yo! 


I've heard you were looking for that  stuff for  a long  time, so I finally found it for you, read more  here <http://rdacundelu.buckingbullbreeder.com/lnziumff>

teg

**Comment by niceteg** [comment]
Hi! 

I've  been  looking for some stuff when by chance I found that! It's so sad,  please read ant tell me what you think <http://favour.ideaboxstudios.com/lngqdvl>

Very truly yours, teg

**Comment by niceteg** [comment]
Hey! 
Here  are some useful  links that I've chosen just for you, check it out <http://target.idearesearchlabs.com/lnplusce>

Best wishes, teg
