### ISSUE TITLE
Read Time Out Error

### ISSUE THREAD

**Issue by shoebhoney** [nostra13/Android-Universal-Image-Loader#1187]
Hi Nostra,

Really great work you have done.

I am getting Time out error,
```

E/ImageLoader: failed to connect to /********** (port 8080) after 5000ms
                                                             java.net.SocketTimeoutException: failed to connect to /52.87.233.241 (port 8080) after 5000ms
                                                                 at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
                                                                 at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                 at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                 at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                 at java.net.Socket.connect(Socket.java:882)
                                                                 at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
                                                                 at com.android.okhttp.Connection.connect(Connection.java:1185)
                                                                 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:395)
                                                                 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
                                                                 at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromNetwork(BaseImageDownloader.java:117)
                                                                 at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:88)
                                                                 at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
                                                                 at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:274)
                                                                 at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:230)
                                                                 at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                 at java.lang.Thread.run(Thread.java:818)
```

**Comment by NoctisDrakon** [comment]
You are getting that error because your device (or emulator) is failing to reach the remote server. Please be sure you are declaring the correct permissions in your AndroidManifest such as INTERNET and the server you're trying to reach is not rejecting the connection because of firewall rules or something like that.
