### ISSUE TITLE
NullPointerException crash in LruDiscCache

### ISSUE THREAD

**Issue by faruktoptas** [nostra13/Android-Universal-Image-Loader#1201]
I have an app in play store. Here is the crash logs i got from crashlitycs:

`Fatal Exception: java.lang.NullPointerException
       at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiscCache.java.io.File get(java.lang.String)(SourceFile:124)
       at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.void run()(SourceFile:72)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
`

I can't reproduce the bug myself.

**Comment by faruktoptas** [comment]
It happens only on General mobile Android 4.2.1 devices.
