### ISSUE TITLE
java.lang.IllegalStateException: ImageLoader must be init with configuration

### ISSUE THREAD

**Issue by setyadew** [nostra13/Android-Universal-Image-Loader#1224]
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{app.kulineryogyakarta/app.name.ActivityPlaceDetail}: java.lang.IllegalStateException: ImageLoader must be init with configuration before using
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2071)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
                                                                           at android.app.ActivityThread.access$600(ActivityThread.java:138)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:213)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4787)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.IllegalStateException: ImageLoader must be init with configuration before using
                                                                           at com.nostra13.universalimageloader.core.ImageLoader.checkConfiguration(ImageLoader.java:613)
                                                                           at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:236)
                                                                           at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:209)
                                                                           at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:316)
                                                                           at app.kulineryogyakarta.ActivityPlaceDetail.onCreate(ActivityPlaceDetail.java:85)
                                                                           at android.app.Activity.performCreate(Activity.java:5008)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2035)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096) 
                                                                           at android.app.ActivityThread.access$600(ActivityThread.java:138) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                           at android.os.Looper.loop(Looper.java:213) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4787) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)`

I found this error after applying android:LargeHeap="true" I test it on android 4.1.2

**Comment by vinitpoojary** [comment]
ImageLoader must be init with configuration before using at 

` UniversalImageLoader universalImageLoader = new UniversalImageLoader(mContext);
        ImageLoader.getInstance().init(universalImageLoader.getConfig());`
