### ISSUE TITLE
Problem with Android 6.0

### ISSUE THREAD

**Issue by fgagneten** [nostra13/Android-Universal-Image-Loader#1230]
With another api version working right
```

 java.io.FileNotFoundException: http://mypage./file.jpg
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
                                                                             at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromNetwork(BaseImageDownloader.java:124)
                                                                             at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:88)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:274)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:230)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
```

**Comment by MageshkumarU** [comment]
I think the reason for error is you may be not provided the permissions required by your API  i.e Android 6.0.

From Android 6.0 (API level 23) or later, the user has to grant your app its permissions while they are running the app. 

You need to use android.permission.READ_EXTERNAL_STORAGE in your manifest file in use permission tag.
