### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by zzg1122** [nostra13/Android-Universal-Image-Loader#1238]
I use Imageloader to download web image,  and the images can be downloaded, but there're a lot of exceptions in console, like below:
java.io.FileNotFoundException: at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
                           at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromNetwork(BaseImageDownloader.java:124)
I don't know how to solve, please help me, thanks in advance~

**Comment by AndrewBryukhov** [comment]
You can try this http://stackoverflow.com/questions/14305765/filenotfoundexception-with-universal-image-loader
