### ISSUE TITLE
There has too much threads run

### ISSUE THREAD

**Issue by VicJcc** [nostra13/Android-Universal-Image-Loader#1253]
488	26515	Monitor	0	0	uil-pool-d-3-thread-425	
489	26516	Monitor	0	0	uil-pool-d-3-thread-426	
490	26518	Monitor	0	0	uil-pool-d-3-thread-427	
491	26519	Monitor	0	0	uil-pool-d-3-thread-428	
492	26520	Monitor	0	0	uil-pool-d-3-thread-429	
493	26522	Monitor	0	0	uil-pool-d-3-thread-430	
494	26523	Monitor	0	0	uil-pool-d-3-thread-431	
495	26524	Monitor	0	0	uil-pool-d-3-thread-432	
496	26526	Monitor	0	0	uil-pool-d-3-thread-433	
497	26527	Monitor	0	0	uil-pool-d-3-thread-434	
498	26528	Monitor	0	0	uil-pool-d-3-thread-435	
499	26530	Monitor	0	0	uil-pool-d-3-thread-436	
500	26531	Monitor	0	0	uil-pool-d-3-thread-437	
501	26532	Monitor	0	0	uil-pool-d-3-thread-438	
502	26534	Monitor	0	0	uil-pool-d-3-thread-439	
503	26535	Monitor	0	0	uil-pool-d-3-thread-440	
504	26536	Monitor	0	0	uil-pool-d-3-thread-441	
505	26538	Monitor	0	0	uil-pool-d-3-thread-442	
506	26540	Monitor	0	0	uil-pool-d-3-thread-443	
507	26541	Monitor	0	0	uil-pool-d-3-thread-444	
508	26543	Monitor	0	0	uil-pool-d-3-thread-445	
509	26544	Monitor	0	0	uil-pool-d-3-thread-446	
510	26545	Monitor	0	0	uil-pool-d-3-thread-447	
511	26547	Monitor	0	0	uil-pool-d-3-thread-448	
512	26548	Monitor	0	0	uil-pool-d-3-thread-449	
513	26549	Monitor	0	0	uil-pool-d-3-thread-450	
514	26552	Monitor	0	0	uil-pool-d-3-thread-451	

here is log from Android Device Monitor,why there has hundreds of threads of imageloader , and their status is Monitor. In this case my imageView will not display bitmap any more.

ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(context)
                .threadPriority(Thread.NORM_PRIORITY - 2)
                .threadPoolSize(2)
                .denyCacheImageMultipleSizesInMemory()
                .diskCacheFileNameGenerator(new Md5FileNameGenerator())
                .tasksProcessingOrder(QueueProcessingType.LIFO)
                .memoryCache(new WeakMemoryCache())
                .memoryCacheSize(3 * 1024 * 1024)
                .diskCacheSize(50 * 1024 * 1024)
                .diskCacheFileCount(100) //缓存的File数量
                .diskCacheExtraOptions(480, 320, null)
                .build();

        ImageLoader.getInstance().init(config);
this is my config of uil, has anyone meet this?Thanks for help!!!

**Comment by VicJcc** [comment]
at com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache.get(DiskLruCache.java:413)	
  at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiskCache.get(LruDiskCache.java:133)	
  at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:72)	
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)	
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)	
  at java.lang.Thread.run(Thread.java:818)	

this is the thread log
