### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by noear** [nostra13/Android-Universal-Image-Loader#1255]
java.lang.OutOfMemoryError: Failed to allocate a 4760012 byte allocation with 497532 free bytes and 485KB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:83)
at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:265)
at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:223)
at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by noear** [comment]
有没有什么解决办法？？？

**Comment by SharpChen** [comment]
Really have no time for development... so I stop project maintaining since Nov 27 :(

**Comment by SharpChen** [comment]
Really have no time for development... so I stop project maintaining since Nov 27 :(
