### ISSUE TITLE
AndroidRuntime: java.lang.IllegalStateException: cache is closed

### ISSUE THREAD

**Issue by NuaaWukesly** [nostra13/Android-Universal-Image-Loader#1272]
10-28 09:37:29.057 31041 32408 E AndroidRuntime: FATAL EXCEPTION: uil-pool-d-3-thread-3
10-28 09:37:29.057 31041 32408 E AndroidRuntime: Process: com.android.xxx, PID: 31041
10-28 09:37:29.057 31041 32408 E AndroidRuntime: java.lang.IllegalStateException: cache is closed
10-28 09:37:29.057 31041 32408 E AndroidRuntime: 	at com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache.checkNotClosed(DiskLruCache.java:642)
10-28 09:37:29.057 31041 32408 E AndroidRuntime: 	at com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache.get(DiskLruCache.java:413)
10-28 09:37:29.057 31041 32408 E AndroidRuntime: 	at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiskCache.get(LruDiskCache.java:133)
10-28 09:37:29.057 31041 32408 E AndroidRuntime: 	at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:72)
10-28 09:37:29.057 31041 32408 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-28 09:37:29.057 31041 32408 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-28 09:37:29.057 31041 32408 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
10-28 09:37:29.057 31041 32322 E AndroidRuntime: FATAL EXCEPTION: uil-pool-d-3-thread-2
10-28 09:37:29.057 31041 32322 E AndroidRuntime: Process: com.android.xxx, PID: 31041
10-28 09:37:29.057 31041 32322 E AndroidRuntime: java.lang.IllegalStateException: cache is closed
10-28 09:37:29.057 31041 32322 E AndroidRuntime: 	at com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache.checkNotClosed(DiskLruCache.java:642)
10-28 09:37:29.057 31041 32322 E AndroidRuntime: 	at com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache.get(DiskLruCache.java:413)
10-28 09:37:29.057 31041 32322 E AndroidRuntime: 	at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiskCache.get(LruDiskCache.java:133)
10-28 09:37:29.057 31041 32322 E AndroidRuntime: 	at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:72)
10-28 09:37:29.057 31041 32322 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-28 09:37:29.057 31041 32322 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-28 09:37:29.057 31041 32322 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

**Comment by webnandroid** [comment]
I think this is due to  the large image size or lopping through images of large sizes
