### ISSUE TITLE
"UIL doesn't support scheme(protocol) by default [gs://" using Firebase

### ISSUE THREAD

**Issue by eduardosejas** [nostra13/Android-Universal-Image-Loader#1306]
I'm using firease storage. 
I'm not getting results to load the images. 
The problem is in Url. 
Can you solve it?

Error:

`UIL doesn't support scheme(protocol) by default [gs://loginteste-795eb.appspot.com/restaurantes/1.png]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
                                                                      java.lang.UnsupportedOperationException: UIL doesn't support scheme(protocol) by default [gs://loginteste-795eb.appspot.com/restaurantes/1.png]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
                                                                          at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromOtherSource(BaseImageDownloader.java:280)
                                                                          at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:99)
                                                                          at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
                                                                          at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:274)
                                                                          at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:230)
                                                                          at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)`

**Comment by akhtar0344** [comment]
`` StorageReference ref = storageReference.child("images")
                ref.putFile(filePath).addOnSuccessListener(new OnSuccessListener<UploadTask.TaskSnapshot>() {
                    @Override
                    public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {
                        Toast.makeText(mContext, "image uploaded", Toast.LENGTH_SHORT).show();

                        Uri image=taskSnapshot.getDownloadUrl();
                        
                
                 myRef.child("images")
                .child(FirebaseAuth.getInstance().getCurrentUser().getUid())
                .child("profile_image")
                .setValue(url);
                    }
                }).addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Toast.makeText(mContext, "image upload failed", Toast.LENGTH_SHORT).show();
                    }
                });``

**Comment by Prashant-6530** [comment]
Uri uri = taskSnapshot.getDownloadUrl() is deprecated. 
You just need to add these lines if you are using Firebase.

uploadTask.addOnSuccessListener(new OnSuccessListener<UploadTask.TaskSnapshot>() {
                @Override
                public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {
                    storageReference.getDownloadUrl().addOnSuccessListener(new OnSuccessListener<Uri>() {
                        @Override
                        public void onSuccess(Uri uri) {
                            Uri firebaseUrl = uri;
                            //Task<Uri> firebaseUrl = taskSnapshot.getStorage().getDownloadUrl();
                            //Toast meassage
                            Toast.makeText(mContext, "Photo upload successful !", Toast.LENGTH_SHORT).show();
                            addPhotoToDatabase(caption, firebaseUrl.toString());

                            Intent intent =new Intent(mContext, MainActivity.class);
                            mContext.startActivity(intent);
                        }
                    });

**Comment by riad73** [comment]
That work perfectly thanks you
