### ISSUE TITLE
Error when loading some images (decoder->decode returned false)

### ISSUE THREAD

**Issue by KSergiy** [nostra13/Android-Universal-Image-Loader#167]
Hi! Thanks for your good library!
I have some problem. My app works with many pictures which loading from network! 98% loading god, but some pics dont loading, and showing errors:

```
02-05 16:47:02.459: D/ImageLoader(14105): Original image (291x300) is going to be subsampled to 162x160 view. Computed scale size - 1
02-05 16:47:02.519: D/dalvikvm(14105): GC_FOR_ALLOC freed 2331K, 22% free 16457K/21027K, paused 35ms
02-05 16:47:02.529: D/skia(14105): --- decoder->decode returned false
02-05 16:47:02.549: E/ImageLoader(14105): null
02-05 16:47:02.549: E/ImageLoader(14105): java.lang.NullPointerException
02-05 16:47:02.549: E/ImageLoader(14105):   at com.universalimageloader.core.LoadAndDisplayImageTask.saveImageOnDisc(LoadAndDisplayImageTask.java:289)
02-05 16:47:02.549: E/ImageLoader(14105):   at com.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:204)
02-05 16:47:02.549: E/ImageLoader(14105):   at com.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:128)
02-05 16:47:02.549: E/ImageLoader(14105):   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
02-05 16:47:02.549: E/ImageLoader(14105):   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-05 16:47:02.549: E/ImageLoader(14105):   at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-05 16:47:02.549: E/ImageLoader(14105):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-05 16:47:02.549: E/ImageLoader(14105):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-05 16:47:02.549: E/ImageLoader(14105):   at java.lang.Thread.run(Thread.java:856)
```

**Comment by bhaveshrangani** [comment]
@nostra13 please put the code for cmyk image format image loading into UIL.
