### ISSUE TITLE
Images aren't loaded after "Clear Cache" in app info

### ISSUE THREAD

**Issue by suhtai** [nostra13/Android-Universal-Image-Loader#168]
When doing a cache clear from the system menu and then opening the app (I think it was opened in the background) the app crashes. Closing the app from recent apps solves the problem but it's not ideal.

This is the error I get:

```
02-08 16:15:46.490: E/ImageLoader(11201): java.io.FileNotFoundException: /storage/sdcard0/Android/data/app.package/cache/-1563422183: open failed: ENOENT (No such file or directory)
02-08 16:15:46.490: E/ImageLoader(11201):   at libcore.io.IoBridge.open(IoBridge.java:416)
02-08 16:15:46.490: E/ImageLoader(11201):   at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
02-08 16:15:46.490: E/ImageLoader(11201):   at java.io.FileOutputStream.<init>(FileOutputStream.java:73)
02-08 16:15:46.490: E/ImageLoader(11201):   at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.saveImageOnDisc(LoadAndDisplayImageTask.java:303)
02-08 16:15:46.490: E/ImageLoader(11201):   at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:204)
02-08 16:15:46.490: E/ImageLoader(11201):   at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:128)
02-08 16:15:46.490: E/ImageLoader(11201):   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
02-08 16:15:46.490: E/ImageLoader(11201):   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
02-08 16:15:46.490: E/ImageLoader(11201):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
02-08 16:15:46.490: E/ImageLoader(11201):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
02-08 16:15:46.490: E/ImageLoader(11201):   at java.lang.Thread.run(Thread.java:856)
02-08 16:15:46.490: E/ImageLoader(11201): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
02-08 16:15:46.490: E/ImageLoader(11201):   at libcore.io.Posix.open(Native Method)
02-08 16:15:46.490: E/ImageLoader(11201):   at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
02-08 16:15:46.490: E/ImageLoader(11201):   at libcore.io.IoBridge.open(IoBridge.java:400)
02-08 16:15:46.490: E/ImageLoader(11201):   ... 10 more
```

**Comment by abuzarsk** [comment]
After clearing cache from setting still image is displaying in the app when internet if off.
