### ISSUE TITLE
ImageLoader must be init with configuration before using

### ISSUE THREAD

**Issue by westlinkin** [nostra13/Android-Universal-Image-Loader#180]
I init the ImageLoader when the app is open. But I still got this problem causes crash.

I got this: java.lang.IllegalStateException: ImageLoader must be init with
configuration before using

this FC is not happen all the time, only occasionally

**Comment by kiran-path** [comment]
Hi, Am facing an issue ,
06-13 14:31:09.890    4566-4566/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.demo.eyeandbuy, PID: 4566
    java.lang.RuntimeException: ImageLoader must be init with configuration before using
            at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:168)
            at com.demo.eyeandbuy.ViewProducts$ImagePagerAdapter.instantiateItem(ViewProducts.java:319)
            at android.support.v4.view.PagerAdapter.instantiateItem(PagerAdapter.java:110)
            at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:837)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:987)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1441)
            at android.view.View.measure(View.java:16834)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1621)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:742)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:607)
            at android.view.View.measure(View.java:16834)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:824)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:500)
            at android.view.View.measure(View.java:16834)
            at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1237)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
            at android.widget.ScrollView.onMeasure(ScrollView.java:326)
            at android.view.View.measure(View.java:16834)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:824)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:500)
            at android.view.View.measure(View.java:16834)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
            at android.view.View.measure(View.java:16834)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
            at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:327)
            at android.view.View.measure(View.java:16834)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2368)
            at android.view.View.measure(View.java:16834)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2246)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1312)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1509)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1189)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6223)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:560)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
            at android.os.Handler.handleCallback(Handler.java:808)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5333)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
            at dalvik.system.NativeStart.main(Native Method)
