### ISSUE TITLE
UIL doesn't support scheme [null] by default.

### ISSUE THREAD

**Issue by Hesamedin** [nostra13/Android-Universal-Image-Loader#190]
Hi Friend,

I'm developer of "Chef Astro" and "Stadium Astro". Your work and effort is awesome. I appreciate.

Recently, I found a problem that I don't know what's the reason. First of all my config is like this:

``` java
public ImageDownloader(Context context) {

        File cacheDir = StorageUtils.getOwnCacheDirectory(context, directoryName + "/Cache");

        // Get singleton instance of ImageLoader
        imageLoader = ImageLoader.getInstance();

        // Create configuration for ImageLoader (all options are optional)
        ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(context).denyCacheImageMultipleSizesInMemory()
                .memoryCache(new UsingFreqLimitedMemoryCache(4 * 1024 * 1024))
                .discCache(new UnlimitedDiscCache(cacheDir))
                .discCacheFileNameGenerator(new HashCodeFileNameGenerator())
                .defaultDisplayImageOptions(
                        new DisplayImageOptions.Builder()
                                .showStubImage(R.drawable.ic_loading_green)
                                .resetViewBeforeLoading()
                                .cacheInMemory()
                                .cacheOnDisc()
                                .imageScaleType(ImageScaleType.IN_SAMPLE_POWER_OF_2)
                                .build())
                .tasksProcessingOrder(QueueProcessingType.FIFO)
                .build();

        // Initialize ImageLoader with created configuration.
        imageLoader.init(config);
    }
```

Based on above configuration if I load an image like
http://www.nasa.gov/images/content/711375main_grail20121205_4x3_946-710.jpg

there is no problem and library works fine. But sometimes library cannot load image. I have a WordPress based weblog. Although, I can load this link
http://www.kamalan.com/wp-content/uploads/2013/02/01.jpg
in browser, library cannot download it. I tried to change directory permission from 644 (for this particular image) to 777 but result was same.

Output in logcat:

```
03-02 01:17:53.580: E/*** TopicAdapter ***(8640): http://www.kamalan.com/wp-content/uploads/2013/02/01.jpg
03-02 01:17:53.590: E/ImageLoader(8640): UIL doesn't support scheme [null] by default. You should implement this support byself
03-02 01:17:53.590: E/ImageLoader(8640): java.lang.UnsupportedOperationException: UIL doesn't support scheme [null] by default. You should implement this support byself
03-02 01:17:53.590: E/ImageLoader(8640):    at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromOtherSource(BaseImageDownloader.java:187)
03-02 01:17:53.590: E/ImageLoader(8640):    at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:90)
03-02 01:17:53.590: E/ImageLoader(8640):    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.saveImageOnDisc(LoadAndDisplayImageTask.java:340)
03-02 01:17:53.590: E/ImageLoader(8640):    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:232)
03-02 01:17:53.590: E/ImageLoader(8640):    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:148)
03-02 01:17:53.590: E/ImageLoader(8640):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
03-02 01:17:53.590: E/ImageLoader(8640):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
03-02 01:17:53.590: E/ImageLoader(8640):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
03-02 01:17:53.590: E/ImageLoader(8640):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
03-02 01:17:53.590: E/ImageLoader(8640):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
03-02 01:17:53.590: E/ImageLoader(8640):    at java.lang.Thread.run(Thread.java:856)
```

I didn't get what does "You should implement this support byself" mean and how to implement it. I appreciate if you give me your feedback. 

Warm regards
Hesam

**Comment by 1234Guz** [comment]
I have the same problem.. I was able to fix it with checking the parameters input from the server. 

if(value/urlfromserver != null) its not working, so I change the logic to this

String tempUrl = value/urlfromserver.trim();

if(tempUrl.contains("null"){
 //value from server is null
} else{
//value is not null put image loader here
}
