### ISSUE TITLE
Export Signed Appliction Package ... Fail

### ISSUE THREAD

**Issue by ElexZhuo** [nostra13/Android-Universal-Image-Loader#286]
I userd universal-image-loader-1.8.4-with-sources.jar
location: ..\libs\universal-image-loader-1.8.4-with-sources.jar

And When I Export Signed Appliction Package ...:

```
 Proguard returned with error code 1. See console
 Note: there were 501 duplicate class definitions.
 Warning: com.nostra13.universalimageloader.core.decode.ImageDecodingInfo: can't find referenced field 'boolean inPreferQualityOverSpeed' in class android.graphics.BitmapFactory$Options
 Warning: com.nostra13.universalimageloader.core.decode.ImageDecodingInfo: can't find referenced field 'android.graphics.Bitmap inBitmap' in class android.graphics.BitmapFactory$Options
 Warning: com.nostra13.universalimageloader.core.decode.ImageDecodingInfo: can't find referenced field 'boolean inMutable' in class android.graphics.BitmapFactory$Options
 Warning: there were 3 unresolved references to program class members.
          Your input classes appear to be inconsistent.
          You may need to recompile them and try again.
          Alternatively, you may have to specify the option 
          '-dontskipnonpubliclibraryclassmembers'.
 java.io.IOException: Please correct the above warnings first.
    at proguard.Initializer.execute(Initializer.java:321)
    at proguard.ProGuard.initialize(ProGuard.java:211)
    at proguard.ProGuard.execute(ProGuard.java:86)
[   at proguard.ProGuard.main(ProGuard.java:492)
```

**Comment by protoss5482** [comment]
i have the same problem witn proguard (Eclipse target=android-21) 
universal-image-loader-1.8.3-with-sources.jar - perfect work
universal-image-loader-1.8.4-with-sources.jar - not work
