### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap 

### ISSUE THREAD

**Issue by d-a-n** [nostra13/Android-Universal-Image-Loader#362]
I'm using the ImageLoader class for showing a podcast cover image on the lock screen. On the second call with the same cover (podcast stopped and started again) I get this error. Looks like the Android RemoteControlClient is calling recycle on the given bitmap too.

I have found this issue #259. The solution was to remove the recycle call. Is there any need for calling recycle anyway?

I think #360 is also related to this issue.

``` java
ImageLoader.getInstance().loadImage(cover,new ImageLoadingListener() {
    @Override
    public void onLoadingStarted(String s, View view) {}
    @Override
    public void onLoadingFailed(String s, View view, FailReason failReason) {}
    @Override
    public void onLoadingComplete(String s, View view, Bitmap bitmap) {
        Log.e(TAG, "bitmap.isRecycled(): "+bitmap.isRecycled()); //first call gives false, second true -> app crashes
        remoteControlClient.editMetadata(false).putBitmap(RemoteControlClient.MetadataEditor.BITMAP_KEY_ARTWORK, bitmap).apply();
    }
    @Override
    public void onLoadingCancelled(String s, View view) {}
});
```

<pre>
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4208ee28
    at android.graphics.Canvas.throwIfRecycled(Canvas.java:1058)
    at android.graphics.Canvas.drawBitmap(Canvas.java:1128)
    at android.media.RemoteControlClient.scaleBitmapIfTooBig(RemoteControlClient.java:1571)
    at android.media.RemoteControlClient.sendArtworkToDisplay(RemoteControlClient.java:1340)
    at android.media.RemoteControlClient.onUpdateDisplayArtworkSize(RemoteControlClient.java:1499)
    at android.media.RemoteControlClient.access$1700(RemoteControlClient.java:65)
    at android.media.RemoteControlClient$EventHandler.handleMessage(RemoteControlClient.java:1251)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5103)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
</pre>

**Comment by cirorizzo** [comment]
I still have this error just on some pictures!!!
