### ISSUE TITLE
RejectedExecutionException

### ISSUE THREAD

**Issue by petrnohejl** [nostra13/Android-Universal-Image-Loader#374]
I updated UIL from 1.8.4 to 1.8.6 and I got this exception. I have never seen this exception in older version. Any idea? Thanks.
- Android 4.3
- universal-image-loader-1.8.6-with-sources.jar

Crashed Thread:

```
java.util.concurrent.RejectedExecutionException: Task com.nostra13.universalimageloader.core.LoadAndDisplayImageTask@418d96e0 rejected from java.util.concurrent.ThreadPoolExecutor@4193b820[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1967)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:782)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1303)
at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:72)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
```

Thread: pool-4-thread-1

```
android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:493)
com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decodeStream(BaseImageDecoder.java:156)
com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:72)
com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:305)
com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:251)
com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:129)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
java.lang.Thread.run(Thread.java:856)
```

Config and options:

```
ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(getApplicationContext())
    .threadPoolSize(3)
    .threadPriority(Thread.MIN_PRIORITY)
    .memoryCache(new UsingFreqLimitedMemoryCache(4 * 1024 * 1024))
    .discCache(new LimitedAgeDiscCache(cacheDir, lifeTime))
    .defaultDisplayImageOptions(DisplayImageOptions.createSimple())
    .build();

mDisplayImageOptions = new DisplayImageOptions.Builder()
    .showStubImage(R.drawable.placeholder_product_list)
    .showImageForEmptyUri(R.drawable.placeholder_product_list)
    .cacheInMemory(true)
    .cacheOnDisc(true)
    .displayer(new SimpleBitmapDisplayer())
    .build();
```

**Comment by Noam-Modai** [comment]
I have the same issue on 1.9.4 (not calling ImageLoader.stop()) : 

java.util.concurrent.RejectedExecutionException: Task com.nostra13.universalimageloader.core.LoadAndDisplayImageTask@42a7e9b0 rejected from java.util.concurrent.ThreadPoolExecutor@423ec530[Shutting down, pool size = 4, active threads = 3, queued tasks = 0, completed tasks = 10]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1334)
       at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:76)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by mr-procrastinator** [comment]
Had same issue too,  v.1.9.3 
```                      
     java.util.concurrent.RejectedExecutionException: Task com.nostra13.unive
                            rsalimageloader.core.LoadAndDisplayImageTask@b5279cc rejected from java.
                            util.concurrent.ThreadPoolExecutor@3023415[Shutting down, pool size = 3,
                             active threads = 1, queued tasks = 0, completed tasks = 2]
                         E      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecu
                            tion(ThreadPoolExecutor.java:2014)
                         E      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor
                            .java:794)
                         E      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecuto
                            r.java:1335)
                         E      at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(Im
                            ageLoaderEngine.java:78)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecu
                            tor.java:1113)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExec
                            utor.java:588)
                         E      at java.lang.Thread.run(Thread.java:818)
```
And I am not using ImageLoader.stop().
