### ISSUE TITLE
StrictMode: Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by mcxiaoke** [nostra13/Android-Universal-Image-Loader#482]
Nexus 4+ kitkat:

12-12 11:34:49.186  29631-29645 E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.io.FileInputStream.<init>(FileInputStream.java:80)
            at java.io.FileInputStream.<init>(FileInputStream.java:105)
            at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromFile(BaseImageDownloader.java:142)
            at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:78)
            at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.getImageStream(BaseImageDecoder.java:83)
            at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:69)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:307)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:253)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:128)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by ChoingHyun** [comment]
I met the same problem at the version 1.9.3

**Comment by hu8373551** [comment]
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
E/StrictMode(20914): java.lang.Throwable: Explicit termination method 'close' not called
E/StrictMode(20914): 	at dalvik.system.CloseGuard.open(CloseGuard.java:184)
E/StrictMode(20914): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:278)
E/StrictMode(20914): 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
E/StrictMode(20914): 	at com.android.okhttp.Connection.connect(Connection.java:107)
E/StrictMode(20914): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
E/StrictMode(20914): 	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
E/StrictMode(20914): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
E/StrictMode(20914): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:355)
E/StrictMode(20914): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:306)
E/StrictMode(20914): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:513)
E/StrictMode(20914): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
E/StrictMode(20914): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromNetwork(BaseImageDownloader.java:117)
E/StrictMode(20914): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:88)
E/StrictMode(20914): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
E/StrictMode(20914): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:274)
E/StrictMode(20914): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:230)
E/StrictMode(20914): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
E/StrictMode(20914): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/StrictMode(20914): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/StrictMode(20914): 	at java.lang.Thread.run(Thread.java:848)
W/System.err(20914): StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
I/Process (20914): Sending signal. PID: 20914 SIG: 9


it still have this problem  ...
