### ISSUE TITLE
java.lang.OutOfMemoryError only on Android 4.4 and 4.3

### ISSUE THREAD

**Issue by Zrelos** [nostra13/Android-Universal-Image-Loader#596]
I have a problem with java.lang.OutOfMemoryError on android 4.4 and 4.3, on the other android version works ok. I use 1.9.1 version

```
java.lang.OutOfMemoryError
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:677)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:507)
at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:872)
at android.content.res.Resources.loadDrawable(Resources.java:3022)
at android.content.res.Resources.getDrawable(Resources.java:1586)
at com.nostra13.universalimageloader.core.DisplayImageOptions.getImageOnLoading(DisplayImageOptions.java:135)
at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:252)
at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:357)
at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:335)
```

```
options = new DisplayImageOptions.Builder()
.showImageOnLoading(R.drawable.ic_stub)
.showImageForEmptyUri(R.drawable.image_error)
.showImageOnFail(R.drawable.image_error)
.cacheInMemory(true)
.cacheOnDisc(true)
.considerExifParams(true)
.imageScaleType(ImageScaleType.EXACTLY_STRETCHED)
.bitmapConfig(Bitmap.Config.RGB_565)
.build();
```

```
ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(context)
.threadPriority(Thread.NORM_PRIORITY - 2)
.denyCacheImageMultipleSizesInMemory()
.discCacheFileNameGenerator(new Md5FileNameGenerator())
.tasksProcessingOrder(QueueProcessingType.LIFO)
//.enableLogging() // Not necessary in common - Problem --> ImageLoader NegativeArraySizeException in 1.8.4 version
//.threadPoolSize(5)
//.memoryCache(new WeakMemoryCache())
.build();
```

**Comment by khavnu** [comment]
it work with me : android:largeHeap
http://stackoverflow.com/questions/11275650/how-to-increase-heap-size-of-an-android-application
