### ISSUE TITLE
OutOfMemoryError sometimes

### ISSUE THREAD

**Issue by RafaRuiz** [nostra13/Android-Universal-Image-Loader#634]
Hello. 

I tried to use this image http://www.flunny.com/file/pic/photo/2014/04/9e29b40c4c73bd166ee2a76f1003773a.jpg (big size)

If the first thing I do is load that image, it's loaded my ImageLoader.

But if I navigate along the app (downloading more images), and after that I try to load it, it gives me an OutOfMemoryError.

```
05-29 12:13:58.528: E/ImageLoader(5041): null
05-29 12:13:58.528: E/ImageLoader(5041): java.lang.OutOfMemoryError
05-29 12:13:58.528: E/ImageLoader(5041):    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
05-29 12:13:58.528: E/ImageLoader(5041):    at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:703)
05-29 12:13:58.528: E/ImageLoader(5041):    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:679)
05-29 12:13:58.528: E/ImageLoader(5041):    at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:78)
05-29 12:13:58.528: E/ImageLoader(5041):    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:285)
05-29 12:13:58.528: E/ImageLoader(5041):    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:231)
05-29 12:13:58.528: E/ImageLoader(5041):    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:141)
05-29 12:13:58.528: E/ImageLoader(5041):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-29 12:13:58.528: E/ImageLoader(5041):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-29 12:13:58.528: E/ImageLoader(5041):    at java.lang.Thread.run(Thread.java:841)
```

How I load it:

``` java
                   HomeActivity.imageLoader.displayImage(item1.getThumb(), im1, HomeActivity.ILoptions, new ImageLoadingListener1(im1, pb1)); // Custom ImageLoadingListener which shows a ProgressBar
```

and my ILoptions and imageLoader are:

``` java
                    ILoptions = new DisplayImageOptions.Builder().cacheInMemory(true).cacheOnDisc(true).build();
        imageLoader.init(ImageLoaderConfiguration.createDefault(HomeActivity.this));
```

**Comment by maysam** [comment]
@nostra13 maybe you can use https://github.com/square/leakcanary in your sample app to see if there is a leak or not

**Comment by stevenchans** [comment]
please don use cacheInMemory  if it is a listview  you will find the memory increase fast
