### ISSUE TITLE
very Strange Error about ->ImageLoader must be init with configuration before using

### ISSUE THREAD

**Issue by ValuesFeng** [nostra13/Android-Universal-Image-Loader#682]
I have already init configuration in myapplication , but got error when i use it .
and I  debug it ,it looks normal.
i use ImageLoader.getInstance().isInited() ,after init it ,It is true,when i use it, it is wrong.
i cant understand.

**Comment by helloHaifei** [comment]
I have the same problem.  I have already init configuration in MyApplication .

java.lang.IllegalStateException: ImageLoader must be init with configuration before using
       at com.nostra13.universalimageloader.core.ImageLoader.checkConfiguration(ImageLoader.java:568)
       at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:208)
       at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:365)
       at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:340)
       at com.autohome.autoclub.common.view.RemoteImageView.setImageUrl(RemoteImageView.java:60)
       at com.autohome.autoclub.business.navigation.ui.adapter.b.getView(ClubBrandPinnedAdapter.java:112)
       at android.widget.AbsListView.obtainView(AbsListView.java:2823)
       at android.widget.ListView.makeAndAddView(ListView.java:1889)
       at android.widget.ListView.fillDown(ListView.java:713)
       at android.widget.ListView.fillFromTop(ListView.java:779)
       at android.widget.ListView.layoutChildren(ListView.java:1684)
       at android.widget.AbsListView.onLayout(AbsListView.java:2627)
       at com.autohome.autoclub.common.view.PinnedHeaderListView.onLayout(PinnedHeaderListView.java:51)
       at android.view.View.layout(View.java:16768)

**Comment by imandaliya** [comment]
Same issue here, already initialized in Application class and application class referenced in Android Menifest, but some how its generate issue.
