### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by tustar** [nostra13/Android-Universal-Image-Loader#685]
I got a lot of  OutOfMemoryError when I use UIL-1.9.3. I had read (Useful Info)[https://github.com/nostra13/Android-Universal-Image-Loader#useful-info] How can i avoid this problem?

```
07-14 12:39:56.242: E/dalvikvm-heap(26405): Out of memory on a 2560016-byte allocation.
07-14 12:39:56.884: E/dalvikvm-heap(26405): Out of memory on a 2560016-byte allocation.
07-14 12:39:57.000: E/ImageLoader(26405): null
07-14 12:39:57.000: E/ImageLoader(26405): java.lang.OutOfMemoryError
07-14 12:39:57.000: E/ImageLoader(26405):   at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
07-14 12:39:57.000: E/ImageLoader(26405):   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:548)
07-14 12:39:57.000: E/ImageLoader(26405):   at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:78)
07-14 12:39:57.000: E/ImageLoader(26405):   at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:264)
07-14 12:39:57.000: E/ImageLoader(26405):   at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:222)
07-14 12:39:57.000: E/ImageLoader(26405):   at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
07-14 12:39:57.000: E/ImageLoader(26405):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
```

``` java
File cacheDir = StorageUtils.getOwnCacheDirectory(
                context.getApplicationContext(), CommonDefine.CACHE_DIR);
        // This configuration tuning is custom. You can tune every option, you
        // may tune some of them,
        // or you can create default configuration by
        // ImageLoaderConfiguration.createDefault(this);
        // method.
        ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(
                context).threadPriority(0).threadPoolSize(5)
                .denyCacheImageMultipleSizesInMemory()
                .memoryCache(new WeakMemoryCache())
                .diskCache(new UnlimitedDiscCache(cacheDir))
                .diskCacheFileNameGenerator(new Md5FileNameGenerator())
                .defaultDisplayImageOptions(DisplayImageOptions.createSimple())
                .tasksProcessingOrder(QueueProcessingType.LIFO).build();

        // Initialize ImageLoader with configuration.
        ImageLoader.getInstance().init(config);
```

``` java
Bitmap.Config bitmapConfig = Bitmap.Config.ARGB_8888;
        if (MiscUtils.isWifi(context)) {
            bitmapConfig = Bitmap.Config.ARGB_8888;
        } else {
            bitmapConfig = Bitmap.Config.RGB_565;
        }

        DisplayImageOptions options = new DisplayImageOptions.Builder()
                .showImageOnLoading(resId).showImageForEmptyUri(resId)
                .showImageOnFail(resId).cacheInMemory(true).cacheOnDisk(true)
                .bitmapConfig(bitmapConfig).considerExifParams(true)
                .imageScaleType(ImageScaleType.IN_SAMPLE_INT).build();

        ImageLoader imageLoader = ImageLoader.getInstance();
        imageLoader.displayImage(url, view, options,
                new ImageDowloaderListener());
```

**Comment by demo1232** [comment]
java.lang.OutOfMemoryError: Failed to allocate a 4665612 byte allocation with 1487384 free bytes and 1452KB until OOM
                                                    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                    at android.graphics.Bitmap.nativeCreate(Native Method)
                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
                                                    at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.considerExactScaleAndOrientatiton(BaseImageDecoder.java:211)
                                                    at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:86)
                                                    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:264)
                                                    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:222)
                                                    at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
