### ISSUE TITLE
UIL doesn't support scheme(protocol) by default [12258]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))

### ISSUE THREAD

**Issue by sm-tester** [nostra13/Android-Universal-Image-Loader#777]
I can't display image from app data folder:

/data/data/com.proba.santaapp/files/JPEG_20141014_213921_.jpg

I pass this path to UIL library such as:

file:///data/data/com.proba.santaapp/files/JPEG_20141014_213921_.jpg

but  i get error.
why ?

**Comment by bhaveshkaila** [comment]
Please provide "file://" before your path like  Strung url="file://"+filepath;

**Comment by boyfox** [comment]
Thanks @bhaveshkaila, I fixed my problem

**Comment by whosmyqueen** [comment]
This path must add "file://" before

**Comment by shubhamsingh9006346** [comment]
09-17 08:22:36.962 24085-26904/com.example.bittu.chathead E/ImageLoader: UIL doesn't support scheme(protocol) by default [file:/null]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
                                                                         java.lang.UnsupportedOperationException: UIL doesn't support scheme(protocol) by default [file:/null]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
                                                                             at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromOtherSource(BaseImageDownloader.java:280)
                                                                             at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:99)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:274)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:230)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
09-17 08:22:36.972 24085-26903/com.example.bittu.chathead E/ImageLoader: UIL doesn't support scheme(protocol) by default [file:/null]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
                                                                         java.lang.UnsupportedOperationException: UIL doesn't support scheme(protocol) by default [file:/null]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
                                                                             at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromOtherSource(BaseImageDownloader.java:280)
                                                                             at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:99)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:274)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:230)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)














can any body help me please

**Comment by boyfox** [comment]
Hi @shubhamsingh9006346 , you passed invalid file url to UIL look to debug:

file:/null - why null?

**Comment by shubhamsingh9006346** [comment]
boyfox

i passed path in a proper way but still i get error....




 You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))

**Comment by shubhamsingh9006346** [comment]
@boyfox  

what should i do please help me because i want add image from gallery and show in other activity.

**Comment by WaxeamRaja** [comment]
Hey dear i have the same problem right now .please help me.

**Comment by boyfox** [comment]
@WaxeamRaja check your passed url
