### ISSUE TITLE
Contact content provider photos not loaded

### ISSUE THREAD

**Issue by jkwiecien** [nostra13/Android-Universal-Image-Loader#836]
When I provide Uri from Contact content provider that looks like this: content://com.android.contacts/contacts/263/photo

the picture won't load

**Comment by JeppeLeth** [comment]
I get the same error (Running KitKat)

02-23 21:03:27.694  24797-24953/com.example.mypackage.debug D/ImageLoader﹕ Start display image task [content://com.android.contacts/contacts/174/photo_120x120]
02-23 21:03:27.694  24797-24955/com.example.mypackage.debug D/ImageLoader﹕ Load image from network [content://com.android.contacts/contacts/174/photo_120x120]
02-23 21:03:27.694  24797-24953/com.example.mypackage.debug D/ImageLoader﹕ Image already is loading. Waiting... [content://com.android.contacts/contacts/174/photo_120x120]
02-23 21:03:27.694  24797-24955/com.example.mypackage.debug D/ImageLoader﹕ Cache image on disk [content://com.android.contacts/contacts/174/photo_120x120]
02-23 21:03:27.704  24797-24955/com.example.mypackage.debug E/ImageLoader﹕ URI: content://com.android.contacts/contacts/174/photo/photo, calling user: com.example.mypackage.debug, calling package:com.example.mypackage.debug
    java.lang.IllegalArgumentException: URI: content://com.android.contacts/contacts/174/photo/photo, calling user: com.example.mypackage.debug, calling package:com.example.mypackage.debug
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
            at android.content.ContentProviderProxy.query(ContentProviderNative.java:463)
            at android.content.ContentResolver.query(ContentResolver.java:476)
            at android.content.ContentResolver.query(ContentResolver.java:419)
            at android.provider.ContactsContract$Contacts.openContactPhotoInputStream(ContactsContract.java:2049)
            at android.provider.ContactsContract$Contacts.openContactPhotoInputStream(ContactsContract.java:2080)
            at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromContent(BaseImageDownloader.java:187)
            at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:90)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:290)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:273)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:229)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:864)

**Comment by SangWoo-Maeng** [comment]
No update in here? Have same problem..
