### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by freecsdn** [nostra13/Android-Universal-Image-Loader#848]
```
"main" prio=5 tid=1 WAIT
  | group="main" sCount=1 dsCount=0 obj=0x418ef638 self=0x417e0228
  | sysTid=11218 nice=0 sched=0/0 cgrp=apps handle=1074569468
  | state=S schedstat=( 25202087301 10061950705 53274 ) utm=2314 stm=204 core=0
  at java.lang.Object.wait(Native Method)
  - waiting on <0x418efa38> (a java.lang.VMThread) held by tid=1 (main)
  at java.lang.Thread.parkFor(Thread.java:1205)
  at sun.misc.Unsafe.park(Unsafe.java:325)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:810)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:843)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1173)
  at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:183)
  at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:259)
  at com.taole.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
  at com.taole.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:275)
  at com.taole.universalimageloader.core.ImageLoader.loadImage(ImageLoader.java:491)
  at com.taole.universalimageloader.core.ImageLoader.loadImage(ImageLoader.java:452)
  at com.taole.universalimageloader.core.ImageLoader.loadImageSync(ImageLoader.java:565)
  at com.taole.universalimageloader.core.ImageLoader.loadImageSync(ImageLoader.java:506)
```

**Comment by VickyZare** [comment]
Hey have you find out solution on that 
please tell me about how you implemented that
