### ISSUE TITLE
Random crashes with RejectedExecutionException

### ISSUE THREAD

**Issue by MufriA** [nostra13/Android-Universal-Image-Loader#871]
My app randomly crashes, I couldn't find any steps to reproduce the issue, FYI I do invoke, ImageLoader.getInstance().stop();  sometime.

How can I avoid this crash, if stop() is reason for this issue, is there any way to stop() without crash?

Any info are appreciated.

```
java.util.concurrent.RejectedExecutionException: Task com.nostra13.universalimageloader.core.LoadAndDisplayImageTask@421a2718 rejected from java.util.concurrent.ThreadPoolExecutor@420e4548[Shutting down, pool size = 3, active threads = 3, queued tasks = 0, completed tasks = 5]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:78)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

My configurations

```
       DisplayImageOptions defaultOptions = new DisplayImageOptions.Builder()
                .cacheInMemory(true)
                .cacheOnDisk(true)
                .showImageOnLoading(R.mipmap.logo_unknown) // resource or drawable
                .showImageOnFail(R.mipmap.logo_unknown)
                .build();

        ImageLoaderConfiguration.Builder builder = new ImageLoaderConfiguration.Builder(this);
        builder.defaultDisplayImageOptions(defaultOptions);
        L.writeLogs(false);

        ImageLoader.getInstance().init(builder.build()); // Do it on Application start
```

**Comment by fergalmoran** [comment]
Have you got anywhere with this, we're experiencing the same issue.

**Comment by pavei** [comment]
+1

**Comment by danilopavei** [comment]
+1

**Comment by leonardobres** [comment]
+1

**Comment by dkmeteor** [comment]
+1

**Comment by duanyanrui** [comment]
still have this issue on 1.9.5

**Comment by md-sohrab-alam** [comment]
getting same issue in 1.9.5
