### ISSUE TITLE
IllegalArgumentException when using FileNameGenerator with extension

### ISSUE THREAD

**Issue by Shashank066** [nostra13/Android-Universal-Image-Loader#873]
I wanted to save the images in cache with their extensions. So, I write my own FileNameGenerator:-

<code>
public class UrlFileNameGenerator implements FileNameGenerator {

	@Override
	public String generate(String url) {
		int lastIndex = url.lastIndexOf('/');
		if(!url.contains("."))
			url = url+".png";
		return url.substring(lastIndex + 1);
	}

}
</code>

I initialize the cache:-

<code>
public static void initUIL(Context context) {
		ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(context)
				.defaultDisplayImageOptions(gridOptions).diskCacheSize(80 * 1024 * 1024)
				.threadPoolSize(2)
				.diskCacheFileNameGenerator(new UrlFileNameGenerator())
				.build();
		ImageLoader.getInstance().init(config);
	}

</code>

The app crashes at launch with the error:-
<code>
FATAL EXCEPTION: uil-pool-d-3-thread-1
Process: com.example.internetwallpaper, PID: 24567
java.lang.IllegalArgumentException: keys must match regex [a-z0-9_-]{1,64}: "1828294.jpg"
at com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache.validateKey(DiskLruCache.java:697)
at com.nostra13.universalimageloader.cache.disc.impl.ext.DiskLruCache.get(DiskLruCache.java:414)
at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiscCache.get(LruDiscCache.java:133)
at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:72)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
</code>

I guess the . isn't allowed in the filename for cache, but then how would the cachefile be saved with extension without .

**Comment by adityap-optimus** [comment]
i have the same problem , want to save images with extensions .

**Comment by HGuangZJH** [comment]
I have a similar problem, but it has some difference. The exception result is:
  [ Caused by: java.lang.IllegalArgumentException: keys must match regex [a-z0-9_-]{1,64}: "" ]
The FileNameGenerator which i use is Md5FileNameGenerator.
I review the source code for this problem, i doubt Md5FileNameGenerator.generate().

Who can answer this question it？
