### ISSUE TITLE
OutOfMemoryError in lib

### ISSUE THREAD

**Issue by volic** [nostra13/Android-Universal-Image-Loader#907]
I know that there are a lot of the same issues in the project.
I have a suggestion.
I talk about #773 issue.
It appeares 
at android.content.res.Resources.getDrawable(Resources.java:682)
at com.nostra13.universalimageloader.core.DisplayImageOptions.getImageOnFail(DisplayImageOptions.java:142)

if we check Android source code at ImageView.resolveUri() we see
```
            try {
                d = rsrc.getDrawable(mResource);
            } catch (Exception e) {
                Log.w("ImageView", "Unable to find resource: " + mResource, e);
                // Don't try again.
                mUri = null;
            }
```

It would be perfect that we could use the trick in your library to avoid crashing.
Thank you.

**Comment by volic** [comment]
It is OutOfMemoryError, It is not Exception. So ImageView behave the same.
