### ISSUE TITLE
Image display in notification causes application crash and device reboot.

### ISSUE THREAD

**Issue by u2gilles** [nostra13/Android-Universal-Image-Loader#908]
I am trying to use UIL to display an image an ongoing notification of a player app.
But when i use the method below, the application 
 - slow down (freeze for a few seconds) though it display the image correctly
 - then crash (please see the log below)
 - and then make my device (samsung S4) reboot.
Do you have any clue what I did wrong. Thanks in advance.

void setNotifImage(String imageUrl) {
   act.mil.imageLoader().loadImage(imageUrl,new SimpleImageLoadingListener() {
     @Override
     public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
        remoteViewsNotifBig.setImageViewBitmap(R.id.notifImagePodcastIV, loadedImage);
        remoteViewsNotif.setImageViewBitmap(R.id.notifImagePodcastIV, loadedImage);
       }
     });
     notificationManager.notify(notificationId, notification);
    }

02-09 18:42:58.780  FATAL EXCEPTION: main
    Process: com.lydia.podcastcutter, PID: 20008
    java.lang.RuntimeException: bad array lengths
            at android.os.Parcel.readIntArray(Parcel.java:820)
            at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:348)
            at android.app.NotificationManager.notify(NotificationManager.java:152)
            at android.app.NotificationManager.notify(NotificationManager.java:116)
            at com.lydia.podcast1.NotificationBoard.setNotifPlayPauseBUT(NotificationBoard.java:124)
            at com.lydia.podcast1.FragmentBoard.updatePlayPauseBUT(FragmentBoard.java:221)
            at com.lydia.podcast1.MMediaPlayer.startPauseMP(MMediaPlayer.java:131)
            at com.lydia.podcast1.MMediaPlayer.playFile(MMediaPlayer.java:46)
            at com.lydia.podcast1.DataPlaylistObject.next(DataPlaylistObject.java:220)
            at com.lydia.podcast1.FragmentBoard$10.onClick(FragmentBoard.java:186)
            at android.view.View.performClick(View.java:4633)
            at android.view.View$PerformClick.run(View.java:19330)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by cre8ivejp** [comment]
I'm getting the same problem here. In my case only happens on devices using 6.0.1
Did you find a solution for this issue?
