### ISSUE TITLE
java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by YonganQiu** [nostra13/Android-Universal-Image-Loader#909]
When I downloaded image from server, I got an java.net.SocketException, the stack info is:
E/ImageLoader(10708): java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
E/ImageLoader(10708): 	at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:591)
E/ImageLoader(10708): 	at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
E/ImageLoader(10708): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:506)
E/ImageLoader(10708): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
E/ImageLoader(10708): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
E/ImageLoader(10708): 	at java.io.InputStream.read(InputStream.java:162)
E/ImageLoader(10708): 	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
E/ImageLoader(10708): 	at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
E/ImageLoader(10708): 	at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
E/ImageLoader(10708): 	at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
E/ImageLoader(10708): 	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
E/ImageLoader(10708): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
E/ImageLoader(10708): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
E/ImageLoader(10708): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
E/ImageLoader(10708): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
E/ImageLoader(10708): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromNetwork(BaseImageDownloader.java:115)
E/ImageLoader(10708): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:86)
E/ImageLoader(10708): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.getImageStream(BaseImageDecoder.java:93)
E/ImageLoader(10708): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:73)
E/ImageLoader(10708): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:264)
E/ImageLoader(10708): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:237)
E/ImageLoader(10708): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
E/ImageLoader(10708): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/ImageLoader(10708): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/ImageLoader(10708): 	at java.lang.Thread.run(Thread.java:848)
E/ImageLoader(10708): Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
E/ImageLoader(10708): 	at libcore.io.Posix.recvfromBytes(Native Method)
E/ImageLoader(10708): 	at libcore.io.Posix.recvfrom(Posix.java:141)
E/ImageLoader(10708): 	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
E/ImageLoader(10708): 	at libcore.io.IoBridge.recvfrom(IoBridge.java:550)
E/ImageLoader(10708): 	... 23 more

But if I access this image url in browser directly, there is no error.

Any one met this problem ever?

**Comment by drduan** [comment]
me too

**Comment by shawyou** [comment]
i have same error log ～

**Comment by Ashishsingh009** [comment]
same bug facing

**Comment by hqglichao** [comment]
i have same error log

**Comment by wpz1016** [comment]
yeah， i have the same error ,but i don't konw how to solve this error.

**Comment by zhangxy1219** [comment]
I have same error, does anyone know how to fix it? Thanks

**Comment by millionsmm** [comment]
Maybe your address have a spelling bug?

**Comment by kachroudi-Nedra** [comment]
i have the same problem! no one has the solution?
