### ISSUE TITLE
UIL is showing and error about not supported scheme for HTTPS, that's normal?

### ISSUE THREAD

**Issue by forlayo** [nostra13/Android-Universal-Image-Loader#915]
```
02-16 19:59:11.907    5084-5851/com.bountycoon E/ImageLoader﹕ UIL doesn't support scheme(protocol) by default [https:/s3-eu-west-1.amazonaws.com/img.bountycoon.com/bet-7g1424113081107457540k8-1424113081840498738.jpg]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
    java.lang.UnsupportedOperationException: UIL doesn't support scheme(protocol) by default [https:/s3-eu-west-1.amazonaws.com/img.bountycoon.com/bet-7g1424113081107457540k8-1424113081840498738.jpg]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
            at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromOtherSource(BaseImageDownloader.java:235)
            at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:97)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:290)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:273)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:229)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

As you can see the url is valid ( and also it works if you open it on browser ): https://s3-eu-west-1.amazonaws.com/img.bountycoon.com/bet-7g1424113081107457540k8-1424113081840498738.jpg

What I doing wrong? https isn't supported or so ?

**Comment by nostra13** [comment]
You passed wrong URL `https:/s3-eu-west-1....`.
Two slashes - `//` must be there.

**Comment by forlayo** [comment]
Ouch! So sorry man! I'm a bit work overloaded today haha. Thanks a lot for you really quick answer ;-)
