### ISSUE TITLE
NullPointerException on Android 5.0 (API 21)

### ISSUE THREAD

**Issue by grebulon** [nostra13/Android-Universal-Image-Loader#927]
I'm getting these [handled] exceptions on devices running Android 5.

```
03-04 04:59:45.296 E/ImageLoader(27386): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.android.okhttp.internal.http.StatusLine.<init>(StatusLine.java:24)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.android.okhttp.Response$Builder.statusLine(Response.java:419)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.android.okhttp.internal.http.JavaApiConverter.createOkResponse(JavaApiConverter.java:116)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.android.okhttp.internal.http.ResponseCacheAdapter.get(ResponseCacheAdapter.java:53)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:269)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromNetwork(BaseImageDownloader.java:113)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:84)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:290)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:273)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:229)
03-04 04:59:45.296 E/ImageLoader(27386): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
03-04 04:59:45.296 E/ImageLoader(27386): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-04 04:59:45.296 E/ImageLoader(27386): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-04 04:59:45.296 E/ImageLoader(27386): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by nostra13** [comment]
Android bug? :)

**Comment by grebulon** [comment]
A quick search implies that it may be related to caching and perhaps disabling caching on the connection for API>=20 will work around it.

**Comment by grebulon** [comment]
Maybe this: https://github.com/gbaldera/TiTouchGallery/issues/6

**Comment by grebulon** [comment]
I managed to work around this by adding the following code to BaseImageDownloader.createConnection
```
if (android.os.Build.VERSION.SDK_INT >= 20)
	conn.setUseCaches(false);
```

**Comment by grebulon** [comment]
The source of this problem is me using a custom ResponseCache that's not implemented properly, and okhttp not handling null responses correctly.
In any case, since the loader uses a private cache (memory/disk) it will be helpful if you add an option to disable the http cache, or just disable it altogether if memory or disk cache are used.
