### ISSUE TITLE
java.lang.ArithmeticException: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long

### ISSUE THREAD

**Issue by yirentianran** [nostra13/Android-Universal-Image-Loader#982]
java.lang.ArithmeticException: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long
at java.math.NativeBN.BN_new(Native Method)
at java.math.BigInt.makeValid(BigInt.java:51)
at java.math.BigInt.putBigEndianTwosComplement(BigInt.java:181)
at java.math.BigInteger.(BigInteger.java:304)
at com.nostra13.universalimageloader.cache.disc.naming.Md5FileNameGenerator.generate(Md5FileNameGenerator.java:38)
at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiscCache.getKey(LruDiscCache.java:224)
at com.nostra13.universalimageloader.cache.disc.impl.ext.LruDiscCache.get(LruDiscCache.java:133)
at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:72)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

**Comment by BinJing** [comment]
andriod 6.0?

**Comment by shaobin0604** [comment]
@BinJing Yes. Have you found any solution ?

**Comment by AndrewLueng** [comment]
I found the same err in my project. Have the problem been solved?

**Comment by kusumakara** [comment]
**i am also facing same issue. Please help me. To resolve the issue.**

exceptionjava.lang.RuntimeException: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long
	at com.android.org.conscrypt.NativeCrypto.ENGINE_load_private_key(Native Method)
	at com.android.org.conscrypt.OpenSSLEngine.getPrivateKeyById(OpenSSLEngine.java:66)
	at android.security.AndroidKeyStore.engineGetKey(AndroidKeyStore.java:86)
	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:372)
	at java.security.KeyStore.getEntry(KeyStore.java:645)
	at obfuscated.adw.b(SourceFile:125)
	at obfuscated.adx.c(SourceFile:81)
	at obfuscated.adx.d(SourceFile:117)
	at com.kodiak.jni.JNIBridge.getStringArrayValueOf(SourceFile:228)
	at com.kn.jni.CdeApiJNI.KN_InitEngine(Native Method)
	at com.kn.jni.CdeApi.KN_InitEngine(SourceFile:239)
	at obfuscated.acq.a(SourceFile:878)
	at obfuscated.agp$12$1.run(SourceFile:479)
	at java.lang.Thread.run(Thread.java:818)
