### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by slawekkrol** [nostra13/Android-Universal-Image-Loader#989]
java.lang.IncompatibleClassChangeError: javax/microedition/khronos/opengles/GL11ExtensionPack
       at android.os.Environment.getPrimaryVolume(Environment.java:219)
       at android.os.Environment.getExternalStorageState(Environment.java:748)
       at com.nostra13.universalimageloader.utils.StorageUtils.getCacheDirectory(StorageUtils.java:70)
       at com.nostra13.universalimageloader.core.DefaultConfigurationFactory.createReserveDiskCacheDir(DefaultConfigurationFactory.java:98)
       at com.nostra13.universalimageloader.core.DefaultConfigurationFactory.createDiskCache(DefaultConfigurationFactory.java:81)
       at com.nostra13.universalimageloader.core.ImageLoaderConfiguration$Builder.initEmptyFieldsWithDefaultValues(ImageLoaderConfiguration.java:580)
       at com.nostra13.universalimageloader.core.ImageLoaderConfiguration$Builder.build(ImageLoaderConfiguration.java:559)
       at MyApplication.initImageLoader(MyApplication.java:118)
       at MyApplication.onCreate(MyApplication.java:49)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4564)
       at android.app.ActivityThread.access$1300(ActivityThread.java:188)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5223)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by nostra13** [comment]
It seems I can do nothing except catching it.
