### ISSUE TITLE
Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by kabouzeid** [nostra13/Android-Universal-Image-Loader#990]
My app force closes due to this exception.

It occurs rare, but it does occur. I already searched my whole project, but there is not a single recycle() call. Also I cannot catch the exception in this case (the calling method is not part of my code).

>Fatal Exception: java.lang.RuntimeException
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@3c4bc1c2

>java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@3c4bc1c2
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:599)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:538)
       at android.widget.ImageView.onDraw(ImageView.java:1176)
       at android.view.View.draw(View.java:15231)
       at android.view.View.updateDisplayListIfDirty(View.java:14167)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15234)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at android.view.View.updateDisplayListIfDirty(View.java:14167)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15234)
       at android.support.v7.widget.RecyclerView.draw()
       at android.view.View.updateDisplayListIfDirty(View.java:14167)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
       at android.view.View.updateDisplayListIfDirty(View.java:14127)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
       at android.view.View.updateDisplayListIfDirty(View.java:14127)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
       at android.view.View.updateDisplayListIfDirty(View.java:14127)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
       at android.view.View.updateDisplayListIfDirty(View.java:14127)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
       at android.view.View.updateDisplayListIfDirty(View.java:14127)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
       at android.view.View.updateDisplayListIfDirty(View.java:14127)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
       at android.view.View.updateDisplayListIfDirty(View.java:14127)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
       at android.view.View.updateDisplayListIfDirty(View.java:14127)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by midou221** [comment]
same here ... Did you find any solution or should I switch to glide or coil ect?
